### ISSUE TITLE
Adrien's review

### ISSUE THREAD

**Issue by aallorant** [math241s24/project01-team-elliottcameronzoe#2]
---
name: Adrien's review
about: Review of project proposal
title: Proposal review
---

Your proposal is great!

### proposal.qmd

The inline code is currently not running- you just need to load the required libraries:

```
Error in `read_csv()`:
! could not find function "read_csv"
                                                                                                            
Execution halted
```
Once I load `tidyverse`, the dataset is read correctly.

### about.qmd

You want to update the `About` section of your website.
  
### _quarto.yml

You want to update the `yml` document.

Specifically, you want to update the website section of the `yml`:

```
website:
  title: Seattle Bike
  navbar:
    right:
      - icon: github
        href: https://github.com/aallorant/project01-seattle-bike
```
